import pandas as pd
from sqlalchemy import create_engine
import time

# --- CONFIGURATION ---
# Format: postgresql://username:password@host:port/database_name
# UPDATE "YOUR_PASSWORD" to your actual Postgres password
DB_URI = "postgresql://postgres:SecurePassword@localhost:5432/telecom_db"

def load_data():
    engine = create_engine(DB_URI)
    
    print("Connecting to PostgreSQL...")
    
    # 1. Load CRM Data
    print("Loading CRM Demographics...")
    df_crm = pd.read_csv('data/raw/crm_demographics.csv')
    df_crm.to_sql('crm_demographics', engine, if_exists='append', index=False)
    
    # 2. Load Recharge Data
    # Note: We don't include transaction_id because Postgres SERIAL will auto-generate it
    print("Loading Recharge Patterns...")
    df_recharge = pd.read_csv('data/raw/recharge_patterns.csv')
    df_recharge.to_sql('recharge_patterns', engine, if_exists='append', index=False)
    
    # 3. Load CDR Data
    # Note: log_id is auto-generated by Postgres
    print("Loading CDR Logs (This might take a few seconds)...")
    df_cdrs = pd.read_csv('data/raw/cdr_logs.csv')
    df_cdrs.to_sql('cdr_logs', engine, if_exists='append', index=False)
    
    print("✅ All data successfully loaded into telecom_db!")

if __name__ == "__main__":
    start_time = time.time()
    load_data()
    print(f"Execution time: {round(time.time() - start_time, 2)} seconds")